name: wordpress

on:
  push:
    branches: [ "main" ]
      
  workflow_dispatch:

env: 
  cloud_region: eu-west-1
  packer-file: ./packer/wordpress.pkr.hcl
  ami-prefics: wordpress-prod-
  docker-file: ./docker/Dockerfile
  terraform-file: ./terraform

jobs:
################################# docker front part ##################################
  build_docker_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          docker build -t footballaws2/wordpress -f ${{ env.docker-file }} .
          docker push footballaws2/wordpress


################################# packer ##################################
  packer_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Packer
        uses: hashicorp/setup-packer@v3.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.cloud_region }}

      - name: Set up Terraform 1.8.5
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        run: cd ${{ env.terraform-file }} && terraform init
  
      - name: Apply Terraform
        run: cd ${{ env.terraform-file }} && terraform output
  
      - name: Get Terraform Outputs
        id: terraform_outputs
        run: |
          cd ${{ env.terraform-file }}
          echo "vpc_id=$(terraform output -raw vpc_id)" >> $GITHUB_ENV
          echo "vpc_id=$(terraform output -raw vpc_id)"
          echo "rds_endpoint=$(terraform output -raw rds_endpoint)" >> $GITHUB_ENV
          echo "redis_endpoint=$(terraform output -raw redis_endpoint)" >> $GITHUB_ENV
          echo "redis_port=$(terraform output -raw redis_port)" >> $GITHUB_ENV
          echo "admin_subnet_ids=$(terraform output -raw admin_subnet_ids_for_packer)" >> $GITHUB_ENV
          echo "security_group_for_parcker=$(terraform output -raw secutity_group_packer_id)" >> $GITHUB_ENV
      
      - name: Retrieve Docker Hub credentials from AWS Secrets Manager
        run: |
          echo "Retrieving secrets from AWS Secrets Manager..."
          DOCKER_HUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id test_mysql_pass --query SecretString --output text | jq -r '.DOCKER_HUB_USERNAME')
          DOCKER_HUB_ACCESS_TOKEN=$(aws secretsmanager get-secret-value --secret-id test_mysql_pass --query SecretString --output text | jq -r '.DOCKER_HUB_ACCESS_TOKEN')
          WORDPRESS_DB_PASSWD=$(aws secretsmanager get-secret-value --secret-id test_mysql_pass --query SecretString --output text | jq -r '.password_for_mysql')
          echo "DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME" >> $GITHUB_ENV
          echo "DOCKER_HUB_ACCESS_TOKEN=$DOCKER_HUB_ACCESS_TOKEN" >> $GITHUB_ENV
          echo "WORDPRESS_DB_PASSWD=$WORDPRESS_DB_PASSWD" >> $GITHUB_ENV
          echo "::add-mask::${{ secrets.vpc_id }}"
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "::add-mask::${{ env.rds_endpoint }}"
          echo "::add-mask::${{ env.redis_endpoint }}"
          echo "::add-mask::${{ env.redis_port }}"
          echo "::add-mask::${{ env.cloud_region }}"
          echo "::add-mask::${{ env.admin_subnet_ids }}"
          echo "::add-mask::${{ env.security_group_for_parcker }}"
          echo "::add-mask::${{ env.DOCKER_HUB_ACCESS_TOKEN }}"
          echo "::add-mask::${{ env.DOCKER_HUB_USERNAME }}"
          echo "::add-mask::${{ env.WORDPRESS_DB_PASSWD }}"
          
      - name: Run Packer
        run: |
          timeline="$(date +'%Y%m%d%H%M%S')"
          packer init ${{ env.packer-file }}
          packer build -var "vpc_id=${{ secrets.vpc_id }}" \
              -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
              -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -var "rds_endpoint=${{ env.rds_endpoint }}" \
              -var "redis_endpoint=${{ env.redis_endpoint }}" \
              -var "redis_port=${{ env.redis_port }}" \
              -var "timestamp=$timeline" \
              -var "aws_region=${{ env.cloud_region }}" \
              -var "admin_subnet_ids"=${{  env.admin_subnet_ids }} \
              -var "security_group_for_parcker"=${{ env.security_group_for_parcker }} \
              -var "DOCKER_HUB_ACCESS_TOKEN"=${{ env.DOCKER_HUB_ACCESS_TOKEN }} \
              -var "DOCKER_HUB_USERNAME"=${{ env.DOCKER_HUB_USERNAME }} \
              -var "wordpress_db_passwd"=${{ env.WORDPRESS_DB_PASSWD }} \
              ${{ env.packer-file }}
